/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface NiceAnim {
    'animationDistance': string;
    'delay': number;
    'direction': 'up' | 'right' | 'left';
    'duration': number;
    'triggerDistance': string;
  }
}

declare global {


  interface HTMLNiceAnimElement extends Components.NiceAnim, HTMLStencilElement {}
  var HTMLNiceAnimElement: {
    prototype: HTMLNiceAnimElement;
    new (): HTMLNiceAnimElement;
  };
  interface HTMLElementTagNameMap {
    'nice-anim': HTMLNiceAnimElement;
  }
}

declare namespace LocalJSX {
  interface NiceAnim extends JSXBase.HTMLAttributes<HTMLNiceAnimElement> {
    'animationDistance'?: string;
    'delay'?: number;
    'direction'?: 'up' | 'right' | 'left';
    'duration'?: number;
    'triggerDistance'?: string;
  }

  interface IntrinsicElements {
    'nice-anim': NiceAnim;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


